"""add order model

Revision ID: 0863f9a3566c
Revises: 151e0618b680
Create Date: 2022-01-08 06:45:41.270409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0863f9a3566c'
down_revision = '151e0618b680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('order_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(120), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
