"""remove product_id column from orders table

Revision ID: 46acac1896d3
Revises: 0863f9a3566c
Create Date: 2022-01-08 07:17:23.167320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46acac1896d3'
down_revision = '0863f9a3566c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_ibfk_1', 'orders', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
