"""remove price in order detail table

Revision ID: 75e0a51b388b
Revises: 6c620c2391b2
Create Date: 2022-01-08 15:40:00.410462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75e0a51b388b'
down_revision = '6c620c2391b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('price', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
