"""add columns in product models

Revision ID: 9aceaebc9118
Revises: ac6d4f5b7aa2
Create Date: 2022-01-09 05:05:47.924781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aceaebc9118'
down_revision = 'ac6d4f5b7aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('most_lead_time', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('lead_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'lead_time')
    op.drop_column('products', 'most_lead_time')
    op.drop_column('products', 'status')
    # ### end Alembic commands ###
