"""add order_details table

Revision ID: 9b035186e75c
Revises: 46acac1896d3
Create Date: 2022-01-08 07:29:34.272334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b035186e75c'
down_revision = '46acac1896d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', mysql.FLOAT(), nullable=True))
    op.add_column('orders', sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('order_details')
    # ### end Alembic commands ###
