"""add price column in order_details table

Revision ID: a018d19399be
Revises: e036187aeeb7
Create Date: 2022-01-08 17:24:38.535096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a018d19399be'
down_revision = 'e036187aeeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'price')
    # ### end Alembic commands ###
