"""add product_id in order_details table

Revision ID: e036187aeeb7
Revises: 75e0a51b388b
Create Date: 2022-01-08 15:42:46.438776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e036187aeeb7'
down_revision = '75e0a51b388b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_details', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.drop_column('order_details', 'product_id')
    # ### end Alembic commands ###
